#!/bin/bash
# Double-click to set up the offline AI engine (Ollama) for NoorDesk.
cd "$(dirname "$0")"

echo "=============================================="
echo "  NoorDesk — Local AI setup (offline, free)"
echo "=============================================="
echo ""

if ! command -v ollama >/dev/null 2>&1; then
  echo "Step 1: Ollama isn't installed yet."
  echo ""
  echo "  • Download it from  https://ollama.com  (opening now…)"
  echo "  • Install it (drag Ollama to Applications, then open it once)."
  echo "  • Come back and run this file again to download the AI model."
  echo ""
  open "https://ollama.com" 2>/dev/null
  read -p "Press Enter to close…"
  exit 0
fi

MODEL="${NOORDESK_OLLAMA_MODEL:-qwen2.5:3b}"
echo "Ollama is installed. Downloading the AI model: $MODEL"
echo "(~2 GB, one time — then it runs fully offline.)"
echo ""
ollama pull "$MODEL"
echo ""
echo "✓ Done! Now:"
echo "  1) Quit NoorDesk (Ctrl+C in its window) and reopen NoorDesk.command."
echo "  2) Send a message — the header pill will show 'Local AI' and replies"
echo "     are now generated by the model."
echo ""
read -p "Press Enter to close…"
